name: ri-aggregation CI

on:
  push:
    branches:
    - rsk_port_initial
    - ci_setup

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rsk_port_initial

      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH

      - name: start-services
        run: |
          docker-compose -f docker-compose-runner.yml down
          docker-compose -f docker-compose-runner.yml up --build -d zk
          ci_run sccache --start-server

      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH

      - name: lints
        run: |
          ci_run zk
          ci_run zk fmt --check
          ci_run zk lint --check

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: rsk_port_initial

      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
        
      - name: start-services
        run: |
          docker-compose -f docker-compose-runner.yml down
          docker-compose -f docker-compose-runner.yml pull
          docker-compose -f docker-compose-runner.yml up --build -d postgres rskj zk 
          ci_run sccache --start-server
 
      - name: init
        run: |
          ci_run ln -s /usr/src/keys/setup keys/setup
          ci_run zk
          ci_run zk run verify-keys unpack
          ci_run zk contract build
          ci_run zk run deploy-erc20 dev
          ci_run zk run deploy-eip1271
          ci_run zk db basic-setup
          ci_run zk run yarn

      - name: restart dev-liquidity-token-watcher and dev-ticker
        run: docker-compose -f docker-compose-runner.yml restart dev-liquidity-token-watcher dev-ticker

      - name: contracts-unit-tests
        run: ci_run zk test contracts

      - name: js-unit-tests
        run: ci_run zk test js

      - name: rust-unit-tests
        run: ci_run zk test server-rust